### ISSUE TITLE
TQDM related issue on Windows - crash

### ISSUE THREAD

**Issue by egedib** [csmliu/AdaDSR#2]
On Windows 10, the test cannot be run, because:
```
Traceback (most recent call last):
  File "test.py", line 101, in <module>
    for i, data in enumerate(tqdm_val):
  File "D:\adasr\solo_py\lib\site-packages\tqdm\std.py", line 1127, in __iter__
    for obj in iterable:
  File "D:\adasr\data\__init__.py", line 56, in __iter__
    for i, data in enumerate(self.dataloader):
  File "D:\adasr\solo_py\lib\site-packages\torch\utils\data\dataloader.py", line 278, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "D:\adasr\solo_py\lib\site-packages\torch\utils\data\dataloader.py", line 682, in __init__
    w.start()
  File "C:\Program Files\Python36\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Program Files\Python36\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Program Files\Python36\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Program Files\Python36\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Program Files\Python36\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'SRDataset.__init__.<locals>.<lambda>'
```
It is Windows-specific bug as I can run it with the exact same parameters on Ubuntu.
Can you look into it?

**Comment by csmliu** [comment]
Sorry that I didn't fully test the code on Windows platform.
You can run this code on Windows by adding an argument `-j0` to disable multi-thread dataloader, which may affect the running efficiency.
By the way, all the experimental results reported in the paper are obtained on the Linux platform.
