### ISSUE TITLE
Install Sparse conv for CUDA-11.1

### ISSUE THREAD

**Issue by Booooooooooo** [csmliu/AdaDSR#9]
Thanks for your work. I am trying to run your code. However, I meet the following error when install sparse conv:

```running install
running bdist_egg
running egg_info
creating masked_conv2d.egg-info
writing masked_conv2d.egg-info/PKG-INFO
writing dependency_links to masked_conv2d.egg-info/dependency_links.txt
writing top-level names to masked_conv2d.egg-info/top_level.txt
writing manifest file 'masked_conv2d.egg-info/SOURCES.txt'
/home/wyb/miniconda3/lib/python3.9/site-packages/torch/utils/cpp_extension.py:381: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
  warnings.warn(msg.format('we could not find ninja.'))
reading manifest file 'masked_conv2d.egg-info/SOURCES.txt'
writing manifest file 'masked_conv2d.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-3.9
creating build/lib.linux-x86_64-3.9/masked_conv2d
copying masked_conv2d/masked_conv.py -> build/lib.linux-x86_64-3.9/masked_conv2d
copying masked_conv2d/__init__.py -> build/lib.linux-x86_64-3.9/masked_conv2d
running build_ext
Traceback (most recent call last):
  File "/data1/wyb/code/AdaDSR/masked_conv2d/setup.py", line 20, in <module>
    setup(
  File "/home/wyb/miniconda3/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/wyb/miniconda3/lib/python3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/wyb/miniconda3/lib/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/wyb/miniconda3/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/wyb/miniconda3/lib/python3.9/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/wyb/miniconda3/lib/python3.9/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/wyb/miniconda3/lib/python3.9/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/wyb/miniconda3/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/wyb/miniconda3/lib/python3.9/site-packages/setuptools/command/bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/wyb/miniconda3/lib/python3.9/site-packages/setuptools/command/bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "/home/wyb/miniconda3/lib/python3.9/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/wyb/miniconda3/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/wyb/miniconda3/lib/python3.9/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/wyb/miniconda3/lib/python3.9/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/home/wyb/miniconda3/lib/python3.9/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/wyb/miniconda3/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/wyb/miniconda3/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/wyb/miniconda3/lib/python3.9/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/wyb/miniconda3/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 404, in build_extensions
    self._check_cuda_version()
  File "/home/wyb/miniconda3/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 781, in _check_cuda_version
    raise RuntimeError(CUDA_MISMATCH_MESSAGE.format(cuda_str_version, torch.version.cuda))
RuntimeError:
The detected CUDA version (10.1) mismatches the version that was used to compile
PyTorch (11.1). Please make sure to use the same CUDA versions.
```

How can I install sparse conv for cuda 11.1?

**Comment by Booooooooooo** [comment]
I've reinstalled my PyTorch. However, when running `python setup.py install`, it seems to get stuck. 
![image](https://user-images.githubusercontent.com/24503757/145784914-fb0d59b3-f39e-422d-80f5-85011f4db22a.png)

Is that normal?

**Comment by CastellanLiu** [comment]
I noticed in your Error report:

> The detected CUDA version (10.1) mismatches the version that was used to compile
> PyTorch (11.1). Please make sure to use the same CUDA versions.

Does it mean that your PyTorch is built with CUDA v11.1 but the CUDA installed on your machine is v10.1?
I guess that you can install a full CUDA v11.x on your machine to solve the problem, or create a new environment by
`conda create -n ENV_NAME anaconda pytorch=1.?? torchvision cudatoolkit=10`
